language: python
python:
  - "3.2"
# command to install dependencies
#install: pip install -r requirements.txt --use-mirrors
install: python setup.py install
# command to run tests
script:
  - python -m unittest -v
  - python -m doctest -v README.rst